### PR TITLE
Cleanup, PEP8 compliance

### PR DESCRIPTION
**Pull request by A-UNDERSCORE-D**
The original code was missing some PEP8 compliance, which made it difficult to read, this adds that, and refactors some of the logic to cleaner versions. It is untested, but there **should** be no output changes

### CODE REVIEW

**Comment by A-UNDERSCORE-D** [comment]
Oh this does make python 3.6 the minimum version this will work on, not sure if you want to do that

**Comment by McJty** [comment]
Preferably not. I only have 3.4 myself

**Comment by McJty** [comment]
Apparently translate doesn't work for this:
    '$L{' + input_name + '}': _input.lower()
ValueError: string keys in translate table must be of length 1

I'll have to revert that part

**Comment by McJty** [comment]
Your change to path joining also wasn't working correctly. It was putting ':' in the path. So reverted that too

**Comment by A-UNDERSCORE-D** [comment]
> Preferably not. I only have 3.4 myself

Ah okay, then yeah any of the fstrings will break



> Apparently translate doesn't work for this:
> '$L{' + input_name + '}': _input.lower()
> ValueError: string keys in translate table must be of length 1
> 
> I'll have to revert that part

Weird. I remember that working. But eh, it was mostly a style choice anyway



> Your change to path joining also wasn't working correctly. It was putting ':' in the path. So reverted that too

Oh. Im an idiot, that should be using `os.sep` which is the directory separator for the current platform, not `os.pathsep` which is the separator for the `PATH` var on the current platform

**Comment by McJty** [comment]
Well I did have 3.6 anyway so I just kept the fstrings. I didn't know that existed. Makes it a bit nicer

**Comment by A-UNDERSCORE-D** [comment]
> Well I did have 3.6 anyway so I just kept the fstrings. I didn't know that existed. Makes it a bit nicer

Yeah they're pretty new, but its very nice to have "real" string interpolation in python.
They are faster / "better" than either of the other two format options -- fstrings are converted to bytecode when the interpreter jits the original source, **and** they're more powerful in that they can run just about anything you want, function calls etc. I have some code somewhere that is an IRC bot entirely in fstrings.

**Pull request merged**
